AOSCOS: fix(regions.c): add missing variable declarations for x1, y1
Fix the following build errors, where GCC >= 14 is more strict about
implicit variable declarations:

regions.c: In function 't1_ChangeDirection':
regions.h:48:49: error: type of 'x2' defaults to 'int' [-Wimplicit-int]
   48 | #define   ChangeDirection(type,R,x,y,dy,x2,y2)  t1_ChangeDirection(type,R,x,y,dy,x2,y2)
      |                                                 ^~~~~~~~~~~~~~~~~~
regions.c:602:6: note: in expansion of macro 'ChangeDirection'
  602 | void ChangeDirection(type, R, x, y, dy, x2, y2)
      |      ^~~~~~~~~~~~~~~
regions.h:48:49: error: type of 'y2' defaults to 'int' [-Wimplicit-int]
   48 | #define   ChangeDirection(type,R,x,y,dy,x2,y2)  t1_ChangeDirection(type,R,x,y,dy,x2,y2)
      |                                                 ^~~~~~~~~~~~~~~~~~
regions.c:602:6: note: in expansion of macro 'ChangeDirection'
  602 | void ChangeDirection(type, R, x, y, dy, x2, y2)
      |      ^~~~~~~~~~~~~~~

Signed-off-by: Mingcong Bai <jeffbai@aosc.io>